### ISSUE TITLE
mcrypt for Windows and Php 8.1?

### ISSUE THREAD

**Issue by Ezyweb-uk** [php/pecl-encryption-mcrypt#11]
Is there a mcrypt dll that works with Php 8.1 on Windows, eg running on XAMPP?

**Comment by amitleuva1987** [comment]
@Ezyweb-uk , did you find any way to install mcrypt in php 8.1 with XAMPP?

**Comment by derickr** [comment]
There are no more Windows builds, as PHP's Windows build-box is no longer available.
