### ISSUE TITLE
Please add the dll version for Windows

### ISSUE THREAD

**Issue by OSPanel** [php/pecl-encryption-mcrypt#14]
Please add the latest version of libraries for Windows (TS version) for all supported PHP versions.
Currently, version 1.0.4 is the latest available for download in the PECL repository.

**Comment by OzanKurt** [comment]
Bump

**Comment by derickr** [comment]
Duplicate of #16, so closing. (Also, adding 'Bump' is unlikely to get a faster response and is considered rude).
