### ISSUE TITLE
php8 mcrypt not enable

### ISSUE THREAD

**Issue by THePhanT00M** [php/pecl-encryption-mcrypt#15]
FROM php:8.2.4-fpm-alpine3.17

RUN apk add --no-cache --virtual .mcrypt-deps  \
    libmcrypt-dev  \
    && docker-php-source extract  \
    && git clone --branch master https://github.com/php/pecl-encryption-mcrypt /usr/src/php/ext/mcrypt/  \
    && docker-php-ext-install mcrypt  \
    && docker-php-ext-enable mcrypt \
    && apk del .mcrypt-deps

build success but not enable
    
 phpinfo : /usr/local/etc/php/conf.d/docker-php-ext-mcrypt.ini

**Comment by derickr** [comment]
Your recipe uses GIT, which you haven't installed. This is not an issue with pecl/mcrypt:

```
3.269 /bin/sh: git: not found
------
Dockerfile:3
--------------------
   1 |     FROM php:8.2.4-fpm-alpine3.17
   2 |     
   3 | >>> RUN apk add --no-cache --virtual .mcrypt-deps libmcrypt-dev && docker-php-source extract && git clone --branch master https://github.com/php/pecl-encryption-mcrypt /usr/src/php/ext/mcrypt/ && docker-php-ext-install mcrypt && docker-php-ext-enable mcrypt && apk del .mcrypt-deps
   4 |     
--------------------

```
