### ISSUE TITLE
Erroneous release numeration on github

### ISSUE THREAD

**Issue by urgodfather** [php/pecl-encryption-mcrypt#18]
It appears that there seems to be a deviation in the versions at some point in the past that is causing confusion. The most recent version with php 8.x support is 1.0.7 but that is causing an issue with the github api. At this current time, the most recent version is 1.0.7. However, making use of the api with intent to obtain the most recent, the dilemma arises where 2.0.7 is listed first.

Behold:

`[
  {
    "name": "2.0.7",
    "zipball_url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/zipball/refs/tags/2.0.7",
    "tarball_url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/tarball/refs/tags/2.0.7",
    "commit": {
      "sha": "ae251198567a546fe63e11480e1bf6f31f21e79c",
      "url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/commits/ae251198567a546fe63e11480e1bf6f31f21e79c"
    },
    "node_id": "MDM6UmVmNzYyMDk0ODE6cmVmcy90YWdzLzIuMC43"
  },
  {
    "name": "2.0.6",
    "zipball_url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/zipball/refs/tags/2.0.6",
    "tarball_url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/tarball/refs/tags/2.0.6",
    "commit": {
      "sha": "f7a22352a26d8e41a11b2075baca328a6622a375",
      "url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/commits/f7a22352a26d8e41a11b2075baca328a6622a375"
    },
    "node_id": "MDM6UmVmNzYyMDk0ODE6cmVmcy90YWdzLzIuMC42"
  },
  {
    "name": "2.0.5",
    "zipball_url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/zipball/refs/tags/2.0.5",
    "tarball_url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/tarball/refs/tags/2.0.5",
    "commit": {
      "sha": "f7dddc84fe3c0be157058bb0495c690596f51939",
      "url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/commits/f7dddc84fe3c0be157058bb0495c690596f51939"
    },
    "node_id": "MDM6UmVmNzYyMDk0ODE6cmVmcy90YWdzLzIuMC41"
  },
  {
    "name": "2.0.4",
    "zipball_url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/zipball/refs/tags/2.0.4",
    "tarball_url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/tarball/refs/tags/2.0.4",
    "commit": {
      "sha": "553a0938dbcce14d5dd36c5595bbe7766f3df2a7",
      "url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/commits/553a0938dbcce14d5dd36c5595bbe7766f3df2a7"
    },
    "node_id": "MDM6UmVmNzYyMDk0ODE6cmVmcy90YWdzLzIuMC40"
  },
  {
    "name": "1.0.7",
    "zipball_url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/zipball/refs/tags/1.0.7",
    "tarball_url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/tarball/refs/tags/1.0.7",
    "commit": {
      "sha": "15949865d9d8eb3a2f06e846d667d55b0033bfa5",
      "url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/commits/15949865d9d8eb3a2f06e846d667d55b0033bfa5"
    },
    "node_id": "MDM6UmVmNzYyMDk0ODE6cmVmcy90YWdzLzEuMC43"
  },
  {
    "name": "1.0.6",
    "zipball_url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/zipball/refs/tags/1.0.6",
    "tarball_url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/tarball/refs/tags/1.0.6",
    "commit": {
      "sha": "afb7052e1fa604c383c57a4354443167522f3953",
      "url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/commits/afb7052e1fa604c383c57a4354443167522f3953"
    },
    "node_id": "MDM6UmVmNzYyMDk0ODE6cmVmcy90YWdzLzEuMC42"
  },
  {
    "name": "1.0.5",
    "zipball_url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/zipball/refs/tags/1.0.5",
    "tarball_url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/tarball/refs/tags/1.0.5",
    "commit": {
      "sha": "d821f9a2912b4bcc369efcadc469fcd48751a245",
      "url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/commits/d821f9a2912b4bcc369efcadc469fcd48751a245"
    },
    "node_id": "MDM6UmVmNzYyMDk0ODE6cmVmcy90YWdzLzEuMC41"
  },
  {
    "name": "1.0.4",
    "zipball_url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/zipball/refs/tags/1.0.4",
    "tarball_url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/tarball/refs/tags/1.0.4",
    "commit": {
      "sha": "fa8ea63fdffaf31cec3609245625b08c2f235e30",
      "url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/commits/fa8ea63fdffaf31cec3609245625b08c2f235e30"
    },
    "node_id": "MDM6UmVmNzYyMDk0ODE6cmVmcy90YWdzLzEuMC40"
  },
  {
    "name": "1.0.3",
    "zipball_url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/zipball/refs/tags/1.0.3",
    "tarball_url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/tarball/refs/tags/1.0.3",
    "commit": {
      "sha": "c672464f01f9735cdbe4bab4e63b4dddda1c7929",
      "url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/commits/c672464f01f9735cdbe4bab4e63b4dddda1c7929"
    },
    "node_id": "MDM6UmVmNzYyMDk0ODE6cmVmcy90YWdzLzEuMC4z"
  },
  {
    "name": "1.0.2",
    "zipball_url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/zipball/refs/tags/1.0.2",
    "tarball_url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/tarball/refs/tags/1.0.2",
    "commit": {
      "sha": "0de85e44695d9a12596f52561e3460e1bda70da2",
      "url": "https://api.github.com/repos/php/pecl-encryption-mcrypt/commits/0de85e44695d9a12596f52561e3460e1bda70da2"
    },
    "node_id": "MDM6UmVmNzYyMDk0ODE6cmVmcy90YWdzLzEuMC4y"
  }
]
`

@derickr while I am aware that the project is seeking a new maintainer, is it possible to adjust this. It would be extremely helpful in cases where manual compilation is necessary and pecl isn't available. 

Thanks in advance!

**Comment by derickr** [comment]
The `2.0.x` tags shouldn't really exist, I'll have a look.

**Comment by derickr** [comment]
I've removed the broken tags.
